/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    MainView: typeof import('./src/components/mars-work/main-view.vue')['default']
    MarsButton: typeof import('./src/components/mars-ui/mars-button/index.vue')['default']
    MarsColor: typeof import('./src/components/mars-ui/mars-color/index.vue')['default']
    MarsDatePicker: typeof import('./src/components/mars-ui/mars-date-picker/index.vue')['default']
    MarsDialog: typeof import('./src/components/mars-ui/mars-dialog/index.vue')['default']
    MarsGui: typeof import('./src/components/mars-ui/mars-gui/index.vue')['default']
    MarsIcon: typeof import('./src/components/mars-ui/mars-icon/index.vue')['default']
    MarsInput: typeof import('./src/components/mars-ui/mars-input/index.vue')['default']
    MarsInputGroup: typeof import('./src/components/mars-ui/mars-input-group/index.vue')['default']
    MarsInputNumber: typeof import('./src/components/mars-ui/mars-input-number/index.vue')['default']
    MarsMap: typeof import('./src/components/mars-work/mars-map.vue')['default']
    MarsRangePicker: typeof import('./src/components/mars-ui/mars-range-picker/index.vue')['default']
    MarsSelect: typeof import('./src/components/mars-ui/mars-select/index.vue')['default']
    MarsSlider: typeof import('./src/components/mars-ui/mars-slider/index.vue')['default']
    MarsSwitch: typeof import('./src/components/mars-ui/mars-switch/index.vue')['default']
    MarsTable: typeof import('./src/components/mars-ui/mars-table/index.vue')['default']
    MarsTextarea: typeof import('./src/components/mars-ui/mars-textarea/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
